#  ____  _                 _     _
# / ___|| |_ __ _ _ __ ___| |__ (_)_ __
# \___ \| __/ _` | '__/ __| '_ \| | '_ \
#  ___) | || (_| | |  \__ \ | | | | |_) |
# |____/ \__\__,_|_|  |___/_| |_|_| .__/
#                                 |_|


command_timeout = 1000
add_newline = false

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character
"""

[character]
format = '$symbol '
success_symbol = '[â¯](green)'
error_symbol = '[âœ—](red)'

[directory]
format = '[$read_only]($read_only_style)[$path]($style) '
style = 'blue'
truncation_length = 0
read_only = 'ğŸ”’'

[git_branch]
format = 'on [$branch]($style) '
style = 'purple'

[git_state]
format = '[\[$state( $progress_current/$progress_total)\]]($style) '
style = 'purple'

[git_status]
format = '[(*$untracked$modified$staged$renamed$deleted$conflicted )($ahead_behind$stashed )]($style)'
style = 'purple'
untracked = 'â€‹'
modified = 'â€‹'
staged = 'â€‹'
renamed = 'â€‹'
deleted = 'â€‹'
conflicted = 'â€‹'
up_to_date = ''
ahead = 'â‡¡'
behind = 'â‡£'
diverged = 'â‡•'
stashed = 'â‰¡'

[cmd_duration]
format = '[$duration]($style)'
style = 'yellow'
