---
#   ____             __ _
#  / ___|___  _ __  / _(_) __ _
# | |   / _ \| '_ \| |_| |/ _` |
# | |__| (_) | | | |  _| | (_| |
#  \____\___/|_| |_|_| |_|\__, |
#                         |___/


homebrew_packages:
  - git
  - neovim
  - tmux
  - starship
  - coreutils
  - zoxide
  - fzf
  - eza
  - fd
  - ripgrep
  - bat
  - jq
  - nmap
  - exiftool
  - btop
  - just
  - ansible
  - kubectl
  - postgresql
  - go
  - php
  - composer

homebrew_casks:
  - google-chrome
  - obsidian
  - ghostty
  - visual-studio-code
  - raycast
  - tailscale
  - docker
  - chatgpt
  - discord
  - spotify
  - iina
  - affinity
  - bambu-studio
  - font-geist
  - font-monaspace

vscode_extensions:
  - enkia.tokyo-night
  - pkief.material-icon-theme
  - github.copilot-chat
  - ms-azuretools.vscode-containers
  - rust-lang.rust-analyzer
  - golang.go
  - bmewburn.vscode-intelephense-client
  - astro-build.astro-vscode
  - unifiedjs.vscode-mdx
  - bradlc.vscode-tailwindcss
  - editorconfig.editorconfig
  - biomejs.biome
  - dbaeumer.vscode-eslint
  - stylelint.vscode-stylelint
  - yoavbls.pretty-ts-errors
  - jock.svg
